version: '3.8'

services:
  app:
    container_name: app
    build: ./app  # Построение образа Django из Dockerfile в папке ./app
    command: gunicorn vik.wsgi:application --bind 0.0.0.0:8000  # Запуск приложения с помощью Gunicorn
    volumes:
      - ./app:/code  # Монтирование локальной папки ./app в контейнер
    expose:
      - "8000"  # Указывает, что контейнер слушает на порту 8000 (только для связи между контейнерами)

  nginx:
    container_name: nginx  # Имя контейнера
    image: nginx:latest  # Используемый образ Nginx
    ports:
      - 80:80  # Прокси для HTTP
      - 443:443  # Прокси для HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Монтирование конфигурации Nginx
      - ./certbot/www:/var/www/certbot  # Монтирование для валидации Certbot
      - ./certbot/conf:/etc/letsencrypt  # Монтирование для сертификатов
    depends_on:
      - app  # Указывает, что Nginx зависит от контейнера app

  certbot:
    image: certbot/certbot  # Используемый образ Certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt  # Монтирование для сертификатов
      - ./certbot/www:/var/www/certbot  # Монтирование для валидации
