version: '3.8'

services:
  app:
    build: ./app
    command: gunicorn vik.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app:/code
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
