version: '3.8'

services:
  # app:
  #   build: ./app
  #   command: gunicorn vik.wsgi:application --bind 0.0.0.0:8000
  #   volumes:
  #     - ./app:/code
  #   expose:
  #     - "8000"
  app:
    container_name: helloworld
    image: crccheck/hello-world
    expose:
      - 8000

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email sosiskavik@gmail.com -d django.sar-bc.ru --agree-tos


